config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
  }

  get 'contacts/new'
  get 'contacts/create'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :public do
    resources :users, only: [:index, :create, :update, :destroy, :edit, :show] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      collection do
        get 'unsubscribe'
        patch "withdrawal"
      end
    end

    resources :posts, only: [:create, :index, :show, :update, :new]
    resources :study_times, only: [:create, :index, :update, :new, :edit, :destroy, :show] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      member do
        patch :stop_time
      end
      collection do
        post  :start_time
        get :top
      end
    end
    resources :study_texts, only: [:create, :update, :destroy]
    resources :study_time_texts, only: [:index]
    resources :learning_details, only: [:create, :update, :destroy, :new]
    resources :photos, only: [:new, :create, :destroy]
    resource :relationships, only: [:create, :destroy]
    get '/search', to: 'searchs#search'
  end
  resources :contacts, only: [:new, :create, :index, :update]

  namespace :admin do
    resources :users, only: [:index, :show] do
      patch "withdrawal"
    end
    resources :study_times, only: [:destroy, :show] do
      resources :post_comments, only: [:destroy]
    end
    get '/search', to: 'searchs#search'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :study_time, optional: true
  validates_uniqueness_of :study_time_id, scope: :user_id
end

app/models/learning_detail.rb
class LearningDetail < ApplicationRecord
  belongs_to :user
  has_many :study_time
  validates :detail, length: { maximum: 30 }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :study_time
  attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :study_time, optional: true
  validates :comment, length: { maximum: 150 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/study_text.rb
class StudyText < ApplicationRecord
  belongs_to :user, optional: true
  has_many :study_time_texts
  has_many :study_times, through: :study_time_texts
  validates :name, length: { maximum: 30 }
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user
  has_many :study_time_texts
  has_many :study_texts, through: :study_time_texts
  belongs_to :learning_detail, optional: true
  has_many :photos, dependent: :destroy
  accepts_attachments_for :photo_images, attachment: :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :study_method, length: { maximum: 150 }
end

app/models/study_time_text.rb
class StudyTimeText < ApplicationRecord
  belongs_to :study_time
  belongs_to :study_text
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :study_texts, dependent: :destroy
  has_many :study_times, dependent: :destroy
  has_many :learning_details, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :study_time_texts, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  has_many :favorites, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :introduction, length: { maximum: 160 }
  validates :name, length: { maximum: 12 }


end

app/controllers/admin/study_times_controller.rb
class Admin::StudyTimesController < ApplicationController
  def destroy
    @study_time = StudyTime.find(params[:id])
    @study_time.destroy
    redirect_to request.referer
  end

  def show
    @study_time = StudyTime.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    if current_user
      top_public_study_times_path # ログイン後に遷移するpathを設定
    else
      admin_users_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_user_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all.order(created_at: :desc)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to request.referer
      flash[:notice] = "お問合せありがとうございました。"
    else
      render :new
    end
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(is_deleted: true)
    redirect_to request.referer
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/admin/study_times_helper.rb
module Admin::StudyTimesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admin/study_times/_index.html.erb
<% study_time.post_comments.each do |comment| %>
  <table>
    <tr>
      <td><%= link_to public_user_path(comment.user) do %>
          <%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
      </td>
      <td><%= comment.comment %></td>
      <td><%= link_to "削除",  admin_study_time_post_comment_path(comment.study_time, comment), method: :delete, "data-confirm" => "本当に削除しますか？" ,class:'delete' %></td>
    </tr>
  </table>
<% end %>

app/views/admin/study_times/_studytimes.html.erb
<% study_times.each do |study_time| %>
    <% hour = ((study_time.end_time.to_i-study_time.start_time.to_i)/60/60).to_i %>
    <% min = (((study_time.end_time.to_i-study_time.start_time.to_i)-(hour*60*60))/60).to_i %>
    <% sec = ((study_time.end_time.to_i-study_time.start_time.to_i)%60).to_i %>
        <table class=tweet width="450" >
            <tr>
                <td><%= link_to public_user_path(study_time.user) do %>
                        <%= attachment_image_tag(study_time.user, :profile_image, :fill, 300, 300, fallback: "no_image.jpg", class:"tweet_icon" )%>&nbsp;&nbsp;
                    <% end %>
                    <%= link_to public_user_path(study_time.user) do %>
                        <%= study_time.user.name %>&nbsp;&nbsp;
                    <% end %>
                    <%= study_time.updated_at%>
                </td>
            </tr>
            <tr>
                <td>&nbsp;&nbsp;<%= study_time.study_method %></td>
            </tr>
            <tr>
                <td align="center">
                    <% study_time.photos.each do |photo| %>
                        <%= attachment_image_tag photo, :image, size:'200x150', class:"post_image" %>
                    <% end %>
                </td>
            </tr>
            <tr>
                <td align="center" class="time">&nbsp;学習時間&nbsp;<%=hour%>時間<%=min%>分<%=sec%>秒&nbsp;</td></div>
            </tr>
            <tr>
                <td align="center" class="learning">&nbsp;学習内容&nbsp;<%= study_time.learning_detail&.detail %></td>
            </tr>
            <tr>
                <td align="center" class="text">使った参考書&nbsp;</td>
            </tr>
                <% study_time.study_texts.each do |study_text| %>
            <tr>
                <td align="center" class="texts"><%= study_text.name %></td>
            </tr>
                <% end %>
        </table>
        <div class="comment">
            <%= link_to public_study_time_path(study_time.id) do %>コメント
                <%=study_time.post_comments.count %>
            <% end %>&nbsp;&nbsp;
            <%= render 'public/favorites/favorite-btn', study_time: study_time %>&nbsp;&nbsp;
            <% if study_time.user == current_user %>
                <%= link_to "削除",  public_study_time_path(study_time.id), method: :delete, "data-confirm" => "本当に削除しますか？" ,class:'delete' %>
            <% end %>
        </div>
<% end %>

app/views/admin/study_times/show.html.erb
<% hour = ((@study_time.end_time.to_i-@study_time.start_time.to_i)/60/60).to_i %>
  <% min = (((@study_time.end_time.to_i-@study_time.start_time.to_i)-(hour*60*60))/60).to_i %>
  <% sec = ((@study_time.end_time.to_i-@study_time.start_time.to_i)%60).to_i %>
    <table class=tweet width="500">
      <tr>
        <td><%= attachment_image_tag(@study_time.user, :profile_image, :fill, 300, 300, fallback: "no_image.jpg", class:"tweet_icon" )%>
        &nbsp;&nbsp;<%= @study_time.user.name %> &nbsp;&nbsp; &nbsp;&nbsp;<%= @study_time.updated_at%></td>
      </tr>
      <tr>
        <td>&nbsp;&nbsp;<%= @study_time.study_method %></td>
      </tr>
      <tr>
        <td align="center">&nbsp;学習時間&nbsp;<%=hour%>時間<%=min%>分<%=sec%>秒&nbsp;</td>
      </tr>
      <tr>
        <td align="center">&nbsp;学習内容&nbsp;<%=@study_time.learning_detail.detail %></td>
      </tr>
      <tr>
        <td align="center">使った参考書</td>
      </tr>
        <% @study_time.study_texts.each do |study_text| %>
          <td align="center"><%= study_text.name %></td>
        <% end %>
        <% @study_time.photos.each do |photo| %>
          <tr>
            <td><%= attachment_image_tag photo, :image, size:'100x100', class:"post_image" %></td>
          </tr>
        <% end %>
          <tr>
      </tr>
    </table>
<%= render 'admin/study_times/index', post_comment: @post_comment, study_time: @study_time, study_times: @study_times %>
<%= link_to "", 'javascript:history.back()', class: "fas fa-undo" %>