config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
  }

  get 'contacts/new'
  get 'contacts/create'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :public do
    resources :users, only: [:index, :create, :update, :destroy, :edit, :show] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      collection do
        get 'unsubscribe'
        patch "withdrawal"
      end
    end

    resources :posts, only: [:create, :index, :show, :update, :new]
    resources :study_times, only: [:create, :index, :update, :new, :edit, :destroy, :show] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      member do
        patch :stop_time
      end
      collection do
        post  :start_time
        get :top
      end
    end
    resources :study_texts, only: [:create, :update, :destroy]
    resources :study_time_texts, only: [:index]
    resources :learning_details, only: [:create, :update, :destroy, :new]
    resources :photos, only: [:new, :create, :destroy]
    resource :relationships, only: [:create, :destroy]
    get '/search', to: 'searchs#search'
  end
  resources :contacts, only: [:new, :create, :index, :update]

  namespace :admin do
    resources :users, only: [:index, :show] do
      patch "withdrawal"
    end
    resources :study_times, only: [:destroy, :show] do
      resources :post_comments, only: [:destroy]
    end
    get '/search', to: 'searchs#search'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :study_time, optional: true
  validates_uniqueness_of :study_time_id, scope: :user_id
end

app/models/learning_detail.rb
class LearningDetail < ApplicationRecord
  belongs_to :user
  has_many :study_time
  validates :detail, length: { maximum: 30 }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :study_time
  attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :study_time, optional: true
  validates :comment, length: { maximum: 150 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/study_text.rb
class StudyText < ApplicationRecord
  belongs_to :user, optional: true
  has_many :study_time_texts
  has_many :study_times, through: :study_time_texts
  validates :name, length: { maximum: 30 }
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user
  has_many :study_time_texts
  has_many :study_texts, through: :study_time_texts
  belongs_to :learning_detail, optional: true
  has_many :photos, dependent: :destroy
  accepts_attachments_for :photo_images, attachment: :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :study_method, length: { maximum: 150 }
end

app/models/study_time_text.rb
class StudyTimeText < ApplicationRecord
  belongs_to :study_time
  belongs_to :study_text
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :study_texts, dependent: :destroy
  has_many :study_times, dependent: :destroy
  has_many :learning_details, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :study_time_texts, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  has_many :favorites, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :introduction, length: { maximum: 160 }
  validates :name, length: { maximum: 12 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    if current_user
      top_public_study_times_path # ログイン後に遷移するpathを設定
    else
      admin_users_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_user_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all.order(created_at: :desc)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to request.referer
      flash[:notice] = "お問合せありがとうございました。"
    else
      render :new
    end
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(is_deleted: true)
    redirect_to request.referer
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>StudyWith</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
        <body>
            <% if admin_signed_in?||user_signed_in? %>
                <nav class="navbar navbar-light bg-warning">
                    <div class="container">
                        <% if user_signed_in? %>
                          <%= link_to "StudyWith", top_public_study_times_path, class:"navbar-brand" %>
                        <% end %>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar9">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse" id="navbar9">
                            <ul class="navbar-nav box d-flex justify-content-end">
                                <% if user_signed_in? %>
                　                    <li><%= link_to " TOP", top_public_study_times_path, class:"fas fa-users nav-link text-light"%></li>
                　                    <li><%= link_to " プロフィール",public_user_path(current_user), class:"fas fa-book-open nav-link text-light"%></li>
                　                    <li><%= link_to " 学習時間", public_study_times_path, class:"fas fa-home nav-link text-light"%></li>
                　                    <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
                　               <% else %>
                　                    <li><%= link_to " 会員一覧", admin_users_path, class:"fas fa-users nav-link text-light"%></li>
                      　              <li><%= link_to "お問い合わせ一覧",contacts_path, class:"fas fa-book-open nav-link text-light"%></li>
                      　              <li><%= link_to " ログアウト", destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" %></li>
                      　         <% end %>
                            </ul>
                        </div>
                    </div>
                </nav>
            <% end %>
          <%= yield %>
      </body>
</html>