config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admin/sessions',
  }

  get 'contacts/new'
  get 'contacts/create'

  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  namespace :public do
    resources :users, only: [:index, :create, :update, :destroy, :edit, :show] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      collection do
        get 'unsubscribe'
        patch "withdrawal"
      end
    end

    resources :posts, only: [:create, :index, :show, :update, :new]
    resources :study_times, only: [:create, :index, :update, :new, :edit, :destroy, :show] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      member do
        patch :stop_time
      end
      collection do
        post  :start_time
        get :top
      end
    end
    resources :study_texts, only: [:create, :update, :destroy]
    resources :study_time_texts, only: [:index]
    resources :learning_details, only: [:create, :update, :destroy, :new]
    resources :photos, only: [:new, :create, :destroy]
    resource :relationships, only: [:create, :destroy]
    get '/search', to: 'searchs#search'
  end
  resources :contacts, only: [:new, :create, :index, :update]

  namespace :admin do
    resources :users, only: [:index, :show] do
      patch "withdrawal"
    end
    resources :study_times, only: [:destroy, :show] do
      resources :post_comments, only: [:destroy]
    end
    get '/search', to: 'searchs#search'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :study_time, optional: true
  validates_uniqueness_of :study_time_id, scope: :user_id
end

app/models/learning_detail.rb
class LearningDetail < ApplicationRecord
  belongs_to :user
  has_many :study_time
  validates :detail, length: { maximum: 30 }
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :study_time
  attachment :image
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :study_time, optional: true
  validates :comment, length: { maximum: 150 }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/study_text.rb
class StudyText < ApplicationRecord
  belongs_to :user, optional: true
  has_many :study_time_texts
  has_many :study_times, through: :study_time_texts
  validates :name, length: { maximum: 30 }
end

app/models/study_time.rb
class StudyTime < ApplicationRecord
  belongs_to :user
  has_many :study_time_texts
  has_many :study_texts, through: :study_time_texts
  belongs_to :learning_detail, optional: true
  has_many :photos, dependent: :destroy
  accepts_attachments_for :photo_images, attachment: :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :study_method, length: { maximum: 150 }
end

app/models/study_time_text.rb
class StudyTimeText < ApplicationRecord
  belongs_to :study_time
  belongs_to :study_text
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :study_texts, dependent: :destroy
  has_many :study_times, dependent: :destroy
  has_many :learning_details, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :study_time_texts, dependent: :destroy
  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  has_many :favorites, dependent: :destroy

  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :introduction, length: { maximum: 160 }
  validates :name, length: { maximum: 12 }


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
    @is_deleted = @user.is_deleted
    @study_times = @user.study_times
    @learning_details = LearningDetail.all
  end

  def destroy
  end

  def withdrawal
    @user = User.find(params[:user_id])
    if @user.is_deleted == false
      @user.update(is_deleted: true)
      reset_session
    else
      @user.update(is_deleted: false)
    end
    redirect_to request.referer
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :study_text_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    if current_user
      top_public_study_times_path # ログイン後に遷移するpathを設定
    else
      admin_users_path
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      new_user_session_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all.order(created_at: :desc)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to request.referer
      flash[:notice] = "お問合せありがとうございました。"
    else
      render :new
    end
  end

  def update
    @contact = Contact.find(params[:id])
    @contact.update(is_deleted: true)
    redirect_to request.referer
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :body)
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searchs_helper.rb
module Admin::SearchsHelper
end

app/helpers/admin/study_texts_helper.rb
module Admin::StudyTextsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/admin/users/_search.html.erb
<table class="table">
   <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">名前</th>
      <th scope="col">Email</th>
      <th scope="col">登録日</th>
      <th scope="col">会員ステータス</th>
    </tr>
  </thead>
    <% users.each do |user| %>
      <tr>
        <td><%= link_to admin_user_path(user.id) do %>
              <%= user.id %>
            <% end %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.email %>
        <td><%= user.created_at%></td>
            <%if user.is_deleted == false %>
              <td>有</td>
            <% else %>
              <td>無</td>
            <%end%>
      </tr>
    <% end %>
    <%= render 'admin/searchs/form' %>
</table>

app/views/admin/users/index.html.erb
<h1>会員一覧</h1>
<%= render 'admin/searchs/form' %>
<table class="table user_index">
   <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">名前</th>
      <th scope="col">Email</th>
      <th scope="col">登録日</th>
      <th scope="col">会員ステータス</th>
    </tr>
  </thead>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to admin_user_path(user.id) do %>
              <%= user.id %>
            <% end %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.email %>
        <td><%= user.created_at%></td>
            <%if user.is_deleted == false %>
              <td>有</td>
            <% else %>
              <td>無</td>
            <%end%>
      </tr>
    <% end %>
</table>

app/views/admin/users/show.html.erb
<div class="container">
   <div class="row">
     <div class="col-sm-4">
<table class="status" >
  <th>会員情報</th>
  <tr>
    <td>名前</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>会員情報</td>
      <%if @is_deleted == false%>
        <td>有</td>
      <% else %>
        <td>無</td>
      <%end%>
  </tr>
  <tr>
    <td><%= link_to "会員ステータスの変更", admin_user_withdrawal_path(@user), method: :PATCH, class: "glyphicon glyphicon-tint btn btn-danger" %></td>
  </tr>
</table>
</div>
<div class="col-sm-8">
<table>
<% @study_times.each do |study_time| %>
        <% hour = ((study_time.end_time.to_i-study_time.start_time.to_i)/60/60).to_i %>
        <% min = (((study_time.end_time.to_i-study_time.start_time.to_i)-(hour*60*60))/60).to_i %>
        <% sec = ((study_time.end_time.to_i-study_time.start_time.to_i)%60).to_i %>
          <table class=tweet width="450">
                  <tr>
                    <td><%= attachment_image_tag(study_time.user, :profile_image, :fill, 300, 300, fallback: "no_image.jpg", class:"tweet_icon" )%>&nbsp;&nbsp;
                        <%= study_time.user.name %>&nbsp;&nbsp;
                        <%= study_time.updated_at%>
                    </td>
                  </tr>
                  <tr>
                    <td>&nbsp;&nbsp;<%= study_time.study_method %></td>
                  </tr>
                   <% study_time.photos.each do |photo| %>
                  <tr>
                    <td><%= attachment_image_tag photo, :image, size:'200x150', class:"post_image" %></td>
                  </tr>
                    <% end %>
                  <tr>
                  <tr>
                    <td align="center" class="time">&nbsp;学習時間&nbsp;<%=hour%>時間<%=min%>分<%=sec%>秒&nbsp;</td>
                  </tr>
                  <tr>
                    <td align="center" class="learning">&nbsp;学習内容&nbsp;<%= study_time.learning_detail&.detail %></td>
                  </tr>
                  <tr>
                    <td align="center" class="text">使った参考書</td>
                  </tr>
                    <% study_time.study_texts.each do |study_text| %>
                  <tr>
                     <td align="center" class="texts"><%= study_text.name %></td>
                  </tr>
                    <% end %>
                    <td align="center"> <%= link_to admin_study_time_path(study_time.id) do %>コメント
                                        <%=study_time.post_comments.count %>
                                        <% end %>&nbsp;&nbsp;
                    <%= link_to "削除",  admin_study_time_path(study_time.id), method: :delete, "data-confirm" => "本当に削除しますか？" ,class:'delete' %></td>
                  </tr>
          </table>
      <% end %>
      </div>
  </div>
</div>